version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8088:8080"
    depends_on: 
      - roach
    environment:
      - PGUSER=${PGUSER:-totoro}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-26257}
      - PGDATABASE=${PGDATABASE:-mydb}
      - SPOTIFY_ID=${SPOTIFY_ID:-123123}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET:-123123}
    deploy:
      restart_policy:
        condition: on-failure

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8089:3000"
    depends_on:
      - backend

  roach:
    image: cockroachdb/cockroach:latest-v25.4
    container_name: roach
    hostname: db
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - roach:/cockroach/cockroach-data
    command: start-single-node --insecure

volumes:
  roach:
