basePath: /api/v1
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  model.IdItem:
    properties:
      id:
        example: 37i9dQZF1DXcBWIGoYBM3M
        type: string
      included_in:
        items:
          $ref: '#/definitions/model.Playlist'
        type: array
      itemType:
        $ref: '#/definitions/model.ItemType'
    type: object
  model.InclusionResponse:
    properties:
      included:
        $ref: '#/definitions/model.InclusionType'
      spotifyID:
        type: string
    type: object
  model.InclusionType:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - Nothing
    - Included
    - Excluded
  model.ItemInclusionRequest:
    properties:
      include:
        type: boolean
      playlistid:
        type: string
      spotid:
        type: string
      type:
        $ref: '#/definitions/model.ItemType'
    required:
    - include
    - playlistid
    - spotid
    - type
    type: object
  model.ItemPlaylistRequest:
    properties:
      cspotid:
        type: string
      pspotid:
        type: string
    required:
    - cspotid
    - pspotid
    type: object
  model.ItemRequest:
    properties:
      parentid:
        type: string
      playlistid:
        type: string
      type:
        $ref: '#/definitions/model.ItemType'
    required:
    - parentid
    - playlistid
    - type
    type: object
  model.ItemResponse:
    properties:
      icon:
        items:
          $ref: '#/definitions/spotify.Image'
        type: array
      included:
        $ref: '#/definitions/model.InclusionType'
      itemType:
        $ref: '#/definitions/model.ItemType'
      name:
        type: string
      sortdata:
        type: integer
      spotifyID:
        type: string
    type: object
  model.ItemType:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - PlaylistItem
    - Artist
    - Album
    - Track
  model.Playlist:
    properties:
      exclusions:
        description: "IncludedIn \t\t  []*Playlist `gorm:\"many2many:playlist_nested_playlists;constraint:OnUpdate:CASCADE,OnDelete:CASCADE\"`"
        items:
          $ref: '#/definitions/model.IdItem'
        type: array
      id:
        example: 37i9dQZF1DXcBWIGoYBM3M
        type: string
      includedPlaylists:
        items:
          $ref: '#/definitions/model.Playlist'
        type: array
      inclusions:
        items:
          $ref: '#/definitions/model.IdItem'
        type: array
      name:
        type: string
    type: object
  model.PlaylistCreateRequest:
    properties:
      name:
        example: My Playlist
        type: string
    required:
    - name
    type: object
  model.PlaylistResponse:
    properties:
      exclusions:
        items:
          $ref: '#/definitions/model.IdItem'
        type: array
      includedPlaylists:
        items:
          $ref: '#/definitions/model.Playlist'
        type: array
      inclusions:
        items:
          $ref: '#/definitions/model.IdItem'
        type: array
      name:
        type: string
      spotifyID:
        type: string
    type: object
  model.SearchRequest:
    properties:
      playlistid:
        type: string
      query:
        type: string
      type:
        $ref: '#/definitions/model.ItemType'
    required:
    - playlistid
    - query
    - type
    type: object
  spotify.Image:
    properties:
      height:
        description: The image height, in pixels.
        type: integer
      url:
        description: The source URL of the image.
        type: string
      width:
        description: The image width, in pixels.
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /playlist:
    delete:
      description: Deletes every playlist record in the database
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Clear all playlists
      tags:
      - playlists
    get:
      description: Responds with the list of all playlists as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.PlaylistResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all playlists
      tags:
      - playlists
    post:
      consumes:
      - application/json
      description: Create a new playlist locally and on Spotify
      parameters:
      - description: Playlist name
        in: body
        name: playlist
        required: true
        schema:
          $ref: '#/definitions/model.PlaylistCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.PlaylistResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Create new playlist
      tags:
      - playlists
  /playlist/{id}:
    delete:
      description: Delete a specific playlist by its ID
      parameters:
      - description: Playlist ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a playlist
      tags:
      - playlists
  /playlist/include:
    post:
      consumes:
      - application/json
      description: Includes one playlist inside another parent playlist
      parameters:
      - description: Playlist Linking Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ItemPlaylistRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PlaylistResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Nest a Playlist
      tags:
      - playlists
  /playlist/item:
    post:
      consumes:
      - application/json
      description: Adds an IdItem to either the inclusions or exclusions of a playlist
      parameters:
      - description: Inclusion/Exclusion Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ItemInclusionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.InclusionResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Include or Exclude an Item
      tags:
      - items
  /playlist/item/undo:
    post:
      consumes:
      - application/json
      description: Removes an IdItem from both inclusions and exclusions of a playlist
      parameters:
      - description: Item to remove
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ItemInclusionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.InclusionResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Undo Include or Exclude
      tags:
      - items
  /search:
    post:
      consumes:
      - application/json
      description: Search Spotify for Artists, Albums, or Tracks based on the provided
        ItemType.
      parameters:
      - description: Search Query and Item Type
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SearchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ItemResponse'
            type: array
        "400":
          description: Invalid Item Type
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Unified Spotify Search
      tags:
      - search
  /spotify/album/tracks:
    post:
      consumes:
      - application/json
      description: Fetches all tracks for a specific Spotify album
      parameters:
      - description: Album and Playlist Context
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ItemResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Tracks by Album
      tags:
      - spotify
  /spotify/artist/albums:
    post:
      consumes:
      - application/json
      description: Fetches albums and singles from Spotify for a specific artist
      parameters:
      - description: Artist and Playlist Context
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ItemResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Albums by Artist
      tags:
      - spotify
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
